services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 3s
      retries: 10
    hostname: postgres
    networks:
      - keycloak-network
  
  keycloak-broker:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak-broker
    command: 
      - start-dev 
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak      
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_DOMAIN_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DOMAIN_DB_USER: keycloak
      KC_DOMAIN_DB_PASSWORD: secret
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./realms/broker/realm-broker.json:/opt/keycloak/data/import/realm-broker.json
      - ./kc-idp-redirect-spi/target/idp-redirect-spi.1.0.0.jar:/opt/keycloak/providers/idp-redirect-spi.1.0.0.jar
      - ./themes/b2b-custom:/opt/keycloak/themes/b2b-custom
    hostname: keycloak-broker
    networks:
      - keycloak-network
  keycloak-idp:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak-idp
    command: 
      - start-dev 
      - --import-realm
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms/idp/realm-idp.json:/opt/keycloak/data/import/realm-idp.json
    hostname: keycloak-idp
    networks:
      - keycloak-network
networks:
  keycloak-network:
    driver: bridge 
volumes:
  postgres_data:

